---
all:
  children:
    nas:
      hosts:
        nas01:
          role_primary: nas
          capabilities: [fast_disk]
    tooling:
      hosts:
        tool01:
          role_primary: tooling
          role_secondary: [monitoring]
          capabilities: [high_cpu]
    proxy:
      hosts:
        proxy01:
          role_primary: proxy
          capabilities: [low_power]
    workers:
      hosts:
        worker01:
          role_primary: worker
          capabilities: [high_cpu, fast_disk]
        worker02:
          role_primary: worker
          capabilities: [low_power]
  vars:
    feature_monitoring_agent: true
