---
- name: Create regular user
  ansible.builtin.user:
    name: "{{ user.username }}"
    shell: /bin/bash
    password: "*"
    state: present
    uid: "{{ user.uid | default(omit) }}"
    home: "/home/{{ user.username }}"
    create_home: true
  become: true

- name: Add user to system groups
  ansible.builtin.user:
    name: "{{ user.username }}"
    groups: "{{ system_groups }}"
    append: true
  become: true

- name: Add SSH keys for regular user
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    key: "{{ item }}"
    state: present
  loop: "{{ user.ssh_keys | default([]) }}"
  when: user.ssh_keys is defined
  become: true
