---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/homelab_ansible
    network_subnet: 192.168.5.0/24
    network_gateway: 192.168.5.1
  children:
    nas:
      hosts: {}
    tooling:
      hosts:
        tooling:
          ansible_host: 192.168.5.10
          role_primary: tooling
          role_secondary: [monitoring]
    proxy:
      hosts: {}
    workers:
      children:
        arch_amd64:
          hosts:
            china4:
              ansible_host: 192.168.5.44
              role_primary: worker
            aws:
              ansible_host: 51.48.178.28
              role_primary: worker

